# Generated by Django 4.1.5 on 2023-02-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_remove_user_id_user_uid_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='addressLine1',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='addressLine2',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='domestic',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(editable=False, max_length=254, unique=True),
        ),
    ]
