name: Deploy to EC2

on:
  push:
    branches:
      - dev
  workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Deploy to EC2
#       uses: fifsky/ssh-action@master
#       with:
#         command: |
#             cd /tmp
#             ls -a
#             echo "env_var:$FIRST_NAME"
#             exit 1
#         host: ${{ secrets.EC2_HOST }}
#         user: ${{ secrets.EC2_USERNAME }}
#         key: ${{ secrets.EC2_SSH_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_KEY  }} 
            EC2_HOST: ${{ secrets.EC2_HOST }}
            EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $EC2_HOST@$EC2_USERNAME '
            ls -a
          '
        