name: Deploy to EC2

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: fifsky/ssh-action@master
      with:
        command: |
            cd /tmp
            ls -a
            echo "env_var:$FIRST_NAME"
            exit 1
        host: ${{ secrets.EC2_HOST }}
        user: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
